name: Deploy to AWS EC2

on:
  push:
    branches:
      - step3

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Zip project files
        run: zip -r spring-gift-order.zip .

      - name: Transfer to EC2
        run: aws s3 cp spring-gift-order.zip s3://${{ secrets.AWS_S3_BUCKET_NAME }}/

      - name: Execute deployment script on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.AWS_EC2_SSH_PRIVATE_KEY }}
          script: |
            sudo apt-get update
            sudo apt-get install -y openjdk-21-jdk # EC2에 Java 설치
            aws s3 cp s3://${{ secrets.AWS_S3_BUCKET_NAME }}/spring-gift-order.zip .
            unzip -o spring-gift-order.zip
            chmod +x ./deploy.sh
            ./deploy.sh